package com.lnet.wmsint.jh.request;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-06-02T20:19:16.033+08:00
 * Generated source version: 3.1.0
 * 
 */
@WebService(targetNamespace = "http://changhongit.com/", name = "ReceiveRequest")
@XmlSeeAlso({ObjectFactory.class})
public interface ReceiveRequest {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "requestReceiveTask", targetNamespace = "http://changhongit.com/", className = "com.lnet.wsmint.jh.request.RequestReceiveTask")
    @WebMethod
    @ResponseWrapper(localName = "requestReceiveTaskResponse", targetNamespace = "http://changhongit.com/", className = "com.lnet.wsmint.jh.request.RequestReceiveTaskResponse")
    public String requestReceiveTask(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            String arg1
    );
}
